<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>KeepConnect.ico</ApplicationIcon>
    <AssemblyName>EasyConnectKeeper</AssemblyName>
    <RootNamespace>EasyConnectKeeper</RootNamespace>
    <Title>EasyConnectKeeper 自动联通程序</Title>
    <Company>Open Source</Company>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="KeepConnect.ico" />
  </ItemGroup>

</Project>